/* PANORAMA OPTICALS — Core App */
let currentCategory='medical',gstEnabled=false;
let billHistory=JSON.parse(localStorage.getItem('po_bills')||'[]');
let inventory=JSON.parse(localStorage.getItem('po_inventory')||'{"medical":[],"optical":[]}');
let customers=JSON.parse(localStorage.getItem('po_customers')||'[]');
let orders=JSON.parse(localStorage.getItem('po_orders')||'[]');
let currentInvTab='medical';
const SHOP={name:'PANORAMA OPTICALS',gstEntity:'SOVA MEDICALS',gstin:'20APTPD0915R1ZP',dlNo:'60/60A',address:'BHALJORIA ROAD, NIRSHA - 828205, DHANBAD',state:'JHARKHAND',stateCode:'20'};
function saveData(){localStorage.setItem('po_bills',JSON.stringify(billHistory));localStorage.setItem('po_customers',JSON.stringify(customers));localStorage.setItem('po_orders',JSON.stringify(orders));localStorage.setItem('po_inventory',JSON.stringify(inventory));}

// INIT
document.addEventListener('DOMContentLoaded',()=>initApp());
function initApp(){document.getElementById('bill-date').valueAsDate=new Date();document.getElementById('bill-id').textContent=generateBillId();addItemRow();addItemRow();renderHistory();if(typeof renderInventory==='function')renderInventory();if(typeof renderOrders==='function')renderOrders();if(typeof renderCustomers==='function')renderCustomers();}

// BILL ID
function generateBillId(){const y=new Date().getFullYear(),r=String(Math.floor(1000+Math.random()*9000)),id='PO'+y+r;return billHistory.some(b=>b.id===id)?generateBillId():id;}

// VIEW TOGGLE
function showView(v){['create','orders','customers','history','inventory'].forEach(x=>{const el=document.getElementById(x+'-view');if(el)el.classList.toggle('hidden',x!==v);const btn=document.getElementById('nav-'+x+'-btn');if(btn)btn.classList.toggle('active',x===v);});if(v==='history')renderHistory();if(v==='inventory'&&typeof renderInventory==='function')renderInventory();if(v==='orders'&&typeof renderOrders==='function')renderOrders();if(v==='customers'&&typeof renderCustomers==='function')renderCustomers();}

// CATEGORY
function setCategory(cat){currentCategory=cat;document.getElementById('cat-medical').classList.toggle('active',cat==='medical');document.getElementById('cat-medical').classList.toggle('medical-active',cat==='medical');document.getElementById('cat-optical').classList.toggle('active',cat==='optical');document.getElementById('rx-card').classList.toggle('hidden',cat!=='optical');document.getElementById('payment-section').classList.toggle('hidden',cat!=='optical');}

// GST
function toggleGST(){gstEnabled=document.getElementById('gst-toggle').checked;const s=document.getElementById('gst-status'),d=document.getElementById('gst-detail');s.textContent=gstEnabled?'GST: ON':'GST: OFF';s.classList.toggle('on',gstEnabled);d.textContent=gstEnabled?'Bill from SOVA MEDICALS & PANORAMA OPTICALS':'Bill from PANORAMA OPTICALS';document.getElementById('cgst-row').style.display=gstEnabled?'flex':'none';document.getElementById('sgst-row').style.display=gstEnabled?'flex':'none';recalculate();}

// ITEMS
function addItemRow(){const tb=document.getElementById('items-body'),i=tb.rows.length+1,tr=document.createElement('tr');tr.innerHTML=`<td>${i}</td><td><input type="text" placeholder="Item name" class="item-name"></td><td><input type="text" placeholder="HSN" class="item-hsn"></td><td><input type="number" min="1" value="1" class="item-qty" oninput="calcRow(this)"></td><td><input type="number" min="0" step="0.01" value="0" class="item-rate" oninput="calcRow(this)"></td><td><input type="number" min="0" max="100" value="0" class="item-disc" oninput="calcRow(this)"></td><td><input type="text" class="item-amt" value="0.00" readonly></td><td><button type="button" class="remove-row-btn" onclick="removeRow(this)"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button></td>`;tb.appendChild(tr);}
function removeRow(b){const tb=document.getElementById('items-body');if(tb.rows.length<=1)return showToast('At least one item required','error');b.closest('tr').remove();reindexRows();recalculate();}
function reindexRows(){const r=document.getElementById('items-body').rows;for(let i=0;i<r.length;i++)r[i].cells[0].textContent=i+1;}
function calcRow(el){const tr=el.closest('tr'),q=parseFloat(tr.querySelector('.item-qty').value)||0,r=parseFloat(tr.querySelector('.item-rate').value)||0,d=parseFloat(tr.querySelector('.item-disc').value)||0;tr.querySelector('.item-amt').value=(q*r*(1-d/100)).toFixed(2);recalculate();}
function recalculate(){let sub=0;document.querySelectorAll('.item-amt').forEach(el=>sub+=parseFloat(el.value)||0);const c=gstEnabled?sub*0.09:0,s=gstEnabled?sub*0.09:0,g=sub+c+s;document.getElementById('subtotal').textContent='₹ '+sub.toFixed(2);document.getElementById('cgst-amount').textContent='₹ '+c.toFixed(2);document.getElementById('sgst-amount').textContent='₹ '+s.toFixed(2);document.getElementById('grand-total').textContent='₹ '+g.toFixed(2);const adv=parseFloat(document.getElementById('advance-paid').value)||0;const bal=Math.max(0,g-adv);const balEl=document.getElementById('balance-due');balEl.textContent='₹ '+bal.toFixed(2);balEl.classList.toggle('balance-zero',bal===0);}

// COLLECT
function collectFormData(){const items=[];for(const row of document.getElementById('items-body').rows){const n=row.querySelector('.item-name').value.trim();if(!n)continue;items.push({name:n,hsn:row.querySelector('.item-hsn').value.trim(),qty:parseFloat(row.querySelector('.item-qty').value)||0,rate:parseFloat(row.querySelector('.item-rate').value)||0,disc:parseFloat(row.querySelector('.item-disc').value)||0,amt:parseFloat(row.querySelector('.item-amt').value)||0});}
const rx=currentCategory==='optical'?{r:{sph:gv('rx-r-sph'),cyl:gv('rx-r-cyl'),axis:gv('rx-r-axis'),add:gv('rx-r-add')},l:{sph:gv('rx-l-sph'),cyl:gv('rx-l-cyl'),axis:gv('rx-l-axis'),add:gv('rx-l-add')}}:null;
return{id:document.getElementById('bill-id').textContent,date:document.getElementById('bill-date').value,category:currentCategory,gst:gstEnabled,customer:{name:gv('cust-name'),phone:gv('cust-phone'),address:gv('cust-address')},items,rx,advance:currentCategory==='optical'?parseFloat(document.getElementById('advance-paid').value)||0:0,deliveryDate:currentCategory==='optical'?document.getElementById('delivery-date').value:''};}
function gv(id){return(document.getElementById(id).value||'').trim();}

// NUMBER TO WORDS
function numberToWords(n){if(n===0)return'Zero';const o=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'],t=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];function c(n){if(n<20)return o[n];if(n<100)return t[Math.floor(n/10)]+(n%10?' '+o[n%10]:'');if(n<1000)return o[Math.floor(n/100)]+' Hundred'+(n%100?' and '+c(n%100):'');if(n<100000)return c(Math.floor(n/1000))+' Thousand'+(n%1000?' '+c(n%1000):'');if(n<10000000)return c(Math.floor(n/100000))+' Lakh'+(n%100000?' '+c(n%100000):'');return c(Math.floor(n/10000000))+' Crore'+(n%10000000?' '+c(n%10000000):'');}const r=Math.floor(n),p=Math.round((n-r)*100);let x='Rupees '+c(r);if(p>0)x+=' and '+c(p)+' Paise';return x+' Only';}

// PDF
function generatePDF(data){if(!data)data=collectFormData();if(!data.customer.name)return showToast('Enter customer name','error');if(data.items.length===0)return showToast('Add at least one item','error');
const{jsPDF}=window.jspdf,doc=new jsPDF('p','mm','a4'),W=210,m=10;let y=m;
doc.setDrawColor(0);doc.setLineWidth(0.5);doc.rect(m,m,W-m*2,148-m*2);
if(data.gst){doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text(SHOP.gstEntity,W/2,y+7,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(SHOP.name,W/2,y+13,{align:'center'});y+=16;}else{doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text(SHOP.name,W/2,y+7,{align:'center'});y+=11;}
doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text(SHOP.address,W/2,y+2,{align:'center'});y+=4;doc.text('State: '+SHOP.state+' | State Code: '+SHOP.stateCode,W/2,y+2,{align:'center'});y+=4;
let dl='DL. NO.: '+SHOP.dlNo;if(data.gst)dl='GSTIN: '+SHOP.gstin+'  |  '+dl;doc.text(dl,W/2,y+2,{align:'center'});y+=5;
doc.setLineWidth(0.3);doc.line(m,y,W-m,y);y+=2;
doc.setFontSize(8);doc.setFont('helvetica','bold');doc.text(data.category==='medical'?'MEDICAL BILL':'OPTICAL BILL',m+3,y+3);
const ds=data.date?new Date(data.date).toLocaleDateString('en-IN'):'';doc.setFont('helvetica','normal');doc.text('Invoice No: '+data.id,W/2-15,y+3);doc.text('Date: '+ds,W-m-3,y+3,{align:'right'});y+=6;
doc.setLineWidth(0.15);doc.line(m,y,W-m,y);y+=2;doc.setFontSize(8);doc.text('Customer: '+data.customer.name,m+3,y+3);if(data.customer.phone)doc.text('Phone: '+data.customer.phone,W-m-3,y+3,{align:'right'});y+=4.5;if(data.customer.address){doc.text('Address: '+data.customer.address,m+3,y+2);y+=4;}y+=1;
// Prescription
if(data.rx&&data.category==='optical'){doc.setLineWidth(0.15);doc.line(m,y,W-m,y);y+=2;doc.setFont('helvetica','bold');doc.setFontSize(7.5);doc.text('EYE PRESCRIPTION',m+3,y+3);y+=4;doc.setFont('helvetica','normal');doc.setFontSize(7);
doc.text('Right (OD): SPH: '+( data.rx.r.sph||'-')+' | CYL: '+(data.rx.r.cyl||'-')+' | AXIS: '+(data.rx.r.axis||'-')+' | ADD: '+(data.rx.r.add||'-'),m+3,y+2);y+=3.5;
doc.text('Left  (OS): SPH: '+(data.rx.l.sph||'-')+' | CYL: '+(data.rx.l.cyl||'-')+' | AXIS: '+(data.rx.l.axis||'-')+' | ADD: '+(data.rx.l.add||'-'),m+3,y+2);y+=4;}
// Items table
const tH=[['#','Item / Description','HSN','Qty','Rate','Disc%','Amount']],tB=data.items.map((it,i)=>[i+1,it.name,it.hsn,it.qty,it.rate.toFixed(2),it.disc+'%',it.amt.toFixed(2)]);
doc.autoTable({startY:y,head:tH,body:tB,margin:{left:m+1,right:m+1},styles:{fontSize:7.5,cellPadding:1.2,lineColor:[0,0,0],lineWidth:0.1},headStyles:{fillColor:[40,40,40],textColor:255,fontStyle:'bold',fontSize:7},columnStyles:{0:{cellWidth:8,halign:'center'},1:{cellWidth:'auto'},2:{cellWidth:20,halign:'center'},3:{cellWidth:12,halign:'center'},4:{cellWidth:22,halign:'right'},5:{cellWidth:14,halign:'center'},6:{cellWidth:24,halign:'right'}},theme:'grid'});
y=doc.lastAutoTable.finalY+2;
const sub=data.items.reduce((s,i)=>s+i.amt,0),cg=data.gst?sub*0.09:0,sg=data.gst?sub*0.09:0,grand=sub+cg+sg;const tX=W-m-3,lX=W-m-55;
doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text('Subtotal:',lX,y+3,{align:'right'});doc.text('Rs. '+sub.toFixed(2),tX,y+3,{align:'right'});y+=4;
if(data.gst){doc.text('CGST (9%):',lX,y+3,{align:'right'});doc.text('Rs. '+cg.toFixed(2),tX,y+3,{align:'right'});y+=4;doc.text('SGST (9%):',lX,y+3,{align:'right'});doc.text('Rs. '+sg.toFixed(2),tX,y+3,{align:'right'});y+=4;}
doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Grand Total:',lX,y+3,{align:'right'});doc.text('Rs. '+grand.toFixed(2),tX,y+3,{align:'right'});y+=5;
// Advance / Balance
if(data.advance>0||data.deliveryDate){doc.setFont('helvetica','normal');doc.setFontSize(8);
if(data.advance>0){doc.text('Advance Paid:',lX,y+3,{align:'right'});doc.text('Rs. '+data.advance.toFixed(2),tX,y+3,{align:'right'});y+=4;const bal=grand-data.advance;doc.setFont('helvetica','bold');doc.text('Balance Due:',lX,y+3,{align:'right'});doc.text('Rs. '+Math.max(0,bal).toFixed(2),tX,y+3,{align:'right'});y+=4;}
if(data.deliveryDate){doc.setFont('helvetica','normal');doc.text('Delivery Date:',lX,y+3,{align:'right'});doc.text(new Date(data.deliveryDate).toLocaleDateString('en-IN'),tX,y+3,{align:'right'});y+=4;}}
// Words + Footer
doc.setLineWidth(0.15);doc.line(m,y,W-m,y);y+=3;doc.setFont('helvetica','italic');doc.setFontSize(7.5);doc.text('Amount in words: '+numberToWords(grand),m+3,y+2);y+=6;
doc.setLineWidth(0.15);doc.line(m,y,W-m,y);y+=2;doc.setFont('helvetica','normal');doc.setFontSize(6.5);doc.text('Terms: Goods once sold will not be taken back or exchanged.',m+3,y+3);
doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text(data.gst?'For '+SHOP.gstEntity:'For '+SHOP.name,W-m-3,y+3,{align:'right'});doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text('Authorized Signatory',W-m-3,y+8,{align:'right'});
doc.save(data.id+'.pdf');
// Save
if(!billHistory.some(b=>b.id===data.id)){const bal=Math.max(0,grand-(data.advance||0));const rec={...data,total:grand,balance:bal,createdAt:new Date().toISOString()};billHistory.unshift(rec);if(typeof upsertCustomer==='function')upsertCustomer(data,grand,bal);if(data.category==='optical'&&data.deliveryDate&&typeof createOrder==='function')createOrder(data,grand,bal);}
saveData();showToast('PDF generated: '+data.id,'success');document.getElementById('bill-id').textContent=generateBillId();}

// HISTORY
function redownloadBill(id){const b=billHistory.find(x=>x.id===id);if(b)generatePDF(b);}
function deleteBill(id){billHistory=billHistory.filter(b=>b.id!==id);saveData();renderHistory();showToast('Bill deleted','error');}
function renderHistory(){const tb=document.getElementById('history-body'),em=document.getElementById('empty-state'),tbl=document.getElementById('history-table');tb.innerHTML='';if(billHistory.length===0){tbl.classList.add('hidden');em.classList.remove('hidden');return;}tbl.classList.remove('hidden');em.classList.add('hidden');
billHistory.forEach(b=>{const tr=document.createElement('tr'),d=b.date?new Date(b.date).toLocaleDateString('en-IN'):'',bal=b.balance||0;tr.innerHTML=`<td style="font-weight:600;color:var(--accent-light)">${b.id}</td><td>${d}</td><td>${b.customer.name}</td><td><span class="badge badge-${b.category}">${b.category}</span></td><td><span class="badge ${b.gst?'badge-gst-on':'badge-gst-off'}">${b.gst?'Yes':'No'}</span></td><td style="font-weight:600">₹ ${(b.total||0).toFixed(2)}</td><td class="${bal>0?'due-highlight':'due-clear'}">₹ ${bal.toFixed(2)}</td><td><div class="history-actions"><button class="hist-btn" onclick="redownloadBill('${b.id}')" title="Download"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7,10 12,15 17,10"/><line x1="12" y1="15" x2="12" y2="3"/></svg></button><button class="hist-btn delete" onclick="deleteBill('${b.id}')" title="Delete"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3,6 5,6 21,6"/><path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/></svg></button></div></td>`;tb.appendChild(tr);});}
function filterHistory(){const q=document.getElementById('search-input').value.toLowerCase();for(const r of document.getElementById('history-body').rows)r.style.display=r.textContent.toLowerCase().includes(q)?'':'none';}
function clearHistory(){if(!confirm('Delete all bill history?'))return;billHistory=[];saveData();renderHistory();showToast('History cleared','error');}

// INVENTORY
function setInvTab(t){currentInvTab=t;document.getElementById('inv-tab-medical').classList.toggle('active',t==='medical');document.getElementById('inv-tab-optical').classList.toggle('active',t==='optical');renderInventory();}
function addInventoryItem(){const n=gv('inv-name'),q=parseFloat(document.getElementById('inv-qty').value)||0,r=parseFloat(document.getElementById('inv-rate').value)||0;if(!n)return showToast('Enter item name','error');if(q<=0)return showToast('Enter quantity','error');if(r<=0)return showToast('Enter rate','error');if(!inventory[currentInvTab])inventory[currentInvTab]=[];inventory[currentInvTab].push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),name:n,hsn:gv('inv-hsn'),qty:q,rate:r,batch:gv('inv-batch'),expiry:document.getElementById('inv-expiry').value,addedAt:new Date().toISOString()});saveData();['inv-name','inv-hsn','inv-qty','inv-rate','inv-batch','inv-expiry'].forEach(x=>document.getElementById(x).value='');renderInventory();showToast('Item added','success');}
function deleteInvItem(id){inventory[currentInvTab]=inventory[currentInvTab].filter(i=>i.id!==id);saveData();renderInventory();showToast('Item removed','error');}
function openEditModal(id){const it=inventory[currentInvTab].find(i=>i.id===id);if(!it)return;document.getElementById('edit-inv-id').value=id;document.getElementById('edit-inv-name').value=it.name;document.getElementById('edit-inv-hsn').value=it.hsn||'';document.getElementById('edit-inv-qty').value=it.qty;document.getElementById('edit-inv-rate').value=it.rate;document.getElementById('edit-inv-batch').value=it.batch||'';document.getElementById('edit-inv-expiry').value=it.expiry||'';document.getElementById('inv-edit-modal').classList.remove('hidden');}
function closeEditModal(){document.getElementById('inv-edit-modal').classList.add('hidden');}
function saveEditItem(){const id=document.getElementById('edit-inv-id').value,it=inventory[currentInvTab].find(i=>i.id===id);if(!it)return;it.name=gv('edit-inv-name');it.hsn=gv('edit-inv-hsn');it.qty=parseFloat(document.getElementById('edit-inv-qty').value)||0;it.rate=parseFloat(document.getElementById('edit-inv-rate').value)||0;it.batch=gv('edit-inv-batch');it.expiry=document.getElementById('edit-inv-expiry').value;saveData();closeEditModal();renderInventory();showToast('Item updated','success');}
function renderInventory(){const items=inventory[currentInvTab]||[],tb=document.getElementById('inv-body'),em=document.getElementById('inv-empty-state'),tbl=document.getElementById('inv-table');tb.innerHTML='';if(items.length===0){tbl.classList.add('hidden');em.classList.remove('hidden');}else{tbl.classList.remove('hidden');em.classList.add('hidden');}let tv=0;items.forEach((it,i)=>{const v=it.qty*it.rate;tv+=v;const tr=document.createElement('tr'),exp=it.expiry?new Date(it.expiry).toLocaleDateString('en-IN'):'—',qc=it.qty<=5?'stock-low':'stock-ok';tr.innerHTML=`<td style="text-align:center;color:var(--text-muted)">${i+1}</td><td style="font-weight:500">${it.name}</td><td>${it.hsn||'—'}</td><td class="${qc}">${it.qty}</td><td>₹ ${it.rate.toFixed(2)}</td><td>${it.batch||'—'}</td><td>${exp}</td><td style="font-weight:600">₹ ${v.toFixed(2)}</td><td><div class="history-actions"><button class="hist-btn" onclick="openEditModal('${it.id}')" title="Edit"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="hist-btn delete" onclick="deleteInvItem('${it.id}')" title="Delete"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3,6 5,6 21,6"/><path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/></svg></button></div></td>`;tb.appendChild(tr);});document.getElementById('inv-total-items').textContent=items.length+' items';document.getElementById('inv-total-value').textContent='₹ '+tv.toFixed(2);}
function filterInventory(){const q=document.getElementById('inv-search').value.toLowerCase();for(const r of document.getElementById('inv-body').rows)r.style.display=r.textContent.toLowerCase().includes(q)?'':'none';}

// RESET & TOAST
function resetForm(){document.getElementById('cust-name').value='';document.getElementById('cust-phone').value='';document.getElementById('cust-address').value='';document.getElementById('items-body').innerHTML='';['rx-r-sph','rx-r-cyl','rx-r-axis','rx-r-add','rx-l-sph','rx-l-cyl','rx-l-axis','rx-l-add'].forEach(x=>document.getElementById(x).value='');document.getElementById('advance-paid').value='0';document.getElementById('delivery-date').value='';addItemRow();addItemRow();document.getElementById('bill-id').textContent=generateBillId();document.getElementById('bill-date').valueAsDate=new Date();recalculate();}
function showToast(msg,type=''){const t=document.getElementById('toast');document.getElementById('toast-msg').textContent=msg;t.className='toast show '+type;setTimeout(()=>t.className='toast hidden',2500);}
